<?php
/**
 * Created by PhpStorm.
 * User: simon
 * Date: 2016/8/24
 * Time: 11:27
 */
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class Register extends TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        \Illuminate\Support\Facades\Session::start();
    }

    /**
     * 注册需要的测试数据
     * @return array
     */
    public function testData() : array
    {//'name'=>str_random(16),
        $data = ['_token'=>csrf_token(),'name'=>str_random(16),'password'=>'123456','email'=>str_random(15).'@qq.com'];
        return $data;
    }

    /**
     * @depends testData
     * @param array $data
     */
    /*public function testValidate(array $data)
    {
        $register = app(\Simon\User\Http\Requests\RegisterRequest::class);
        $b = $register->getValidatorInstance();
        dd($b);
    }*/

    /**
     * @depends testData
     * @param array $data
     */
    public function testRegister(array $data)
    {
        //$Register = new \Simon\User\Services\RegisterService(new \Simon\User\Repositorys\UserRepository(new \Simon\User\Models\User()));
        $register = app(\Simon\User\Services\RegisterService::class);
        $user = $register->register($data)->getUser();

        return $user->id;
    }



    /**
     * @depends testRegister
     * @param int $userId
     */
    public function testMailCode(int $userId)
    {
        $mailCode = app(\Simon\User\Services\UserMailCodeService::class);
        $hash = $mailCode->generate($userId);

        return $hash;
//dd($hash);
        //$this->assertString($hash);
    }

    /**
     * @depends testRegister
     * @depends testMailCode
     * @param string $hash
     */
    public function testSendMail(int $userId,string $hash)
    {
        $user = (new \Simon\User\Models\User())->find($userId);

        $mailer = new \Simon\User\Mails\RegisterMail($user,$hash);

        mailer($user->email,$mailer);
    }

    /**
     * @depends testData
     */
//    public function testValidator(array $data)
//    {
////        $request = app(\Simon\User\Http\Requests\RegisterRequest::class);
////        dd($request);
////        $validator = $request->getMessages();
////        dd($validator);
//    }

    /**
     *
     * @depends testData
     */
    /*public function testRegister(array $data)
    {

        $Register = new \Simon\User\Services\RegisterService(new \Simon\User\Repositorys\UserRepository(new \Simon\User\Models\User()));
//
//        $data = ['_token'=>csrf_token(),'name'=>str_random(16),'password'=>'123456','email'=>str_random(15).'@qq.com'];
        $b = $Register->register($data)->getUser();
//dd($b);
       // $this->assert
//        $this->submitForm('#submit',$data);
//
//        return;
//        $this->assertResponseOk();

        $response = $this->post('auth/register',$data);
        dd($response->getStatusMessage());
//        $this->assertEquals('success');
//        $this->anOne
//        $this->submitForm('123',$data);

//        $response = $this->post('auth/register',$data);
//        dd($response->getResult());
//        dd($response->getStatusMessage());
    }*/

    /*
    public function testAbc()
    {
        $array = [];
        $this->assertEmpty($array);
    }*/

}